[package]
name = "designpattern_rust"
version = "0.1.0"
authors = ["Toshiya Nakakura <nakakura@me.com>"]

[[bin]]
name = "command"
path = "src/command/main.rs"

[[bin]]
name = "state"
path = "src/state/main.rs"

[dependencies]
rand = "0.3"
